from uagents import Model
from pydantic.v1 import Field
from typing import List, Dict, Any, Optional
from uuid import UUID, uuid4

class PlannerTask(Model):
    """
    Represents a single, discrete task generated by the planning agent.
    """
    task_id: int = Field(description="A unique identifier for the task within the plan.")
    agent_name: str = Field(description="The name of the agent responsible for this task (e.g., 'FundamentalsAgent').")
    tool_name: str = Field(description="The specific tool the agent needs to use (e.g., 'get_company_overview').")
    instructions: str = Field(description="The detailed instructions for the agent to complete the task.")
    status: str = Field(default="pending", description="The current status of the task ('pending', 'completed', 'failed').")
    
class TaskResult(Model):
    """
    Stores the output of a single completed task.
    """
    task_id: int = Field(description="The ID of the task that was completed.")
    result: str = Field(description="The output data produced by the agent, serialized as a string.")

class SessionContext(Model):
    """
    The Model Context Protocol (MCP) object for StockSage.

    This object encapsulates the entire state of a user's query as it is processed
    by the distributed agent system. It is created by the APIGatewayAgent, updated
    by the QueryPlannerAgent, and then passed from one agent to the next,
    accumulating results along the way.
    """
    session_id: str = Field(description="A unique identifier for the entire query session.")
    original_query: str = Field(description="The initial, unmodified natural language query from the user.")
    
    # --- Planning Stage ---
    planned_tasks: List[PlannerTask] = Field(default_factory=list, description="The sequence of tasks generated by the planner.")
    
    # --- Execution Stage ---
    execution_history: List[TaskResult] = Field(default_factory=list, description="A log of results from each agent that has processed this context.")
    
    # --- Final Output ---
    final_report: Optional[str] = Field(None, description="The final structured report summarizing the findings.")
    status: str = Field(default="planning", description="The current status of the session (e.g., 'planning', 'plan_created', 'executing', 'completed', 'failed').")


# --- Agent-Specific Request/Response Models ---

class PlannerQueryRequest(Model):
    """Request model for the QueryPlannerAgent."""
    query: str
    session_id: str

class DataAgentRequest(Model):
    """
    Generic request model for data acquisition agents.
    It wraps the session context.
    """
    context: SessionContext
